### ISSUE TITLE
CalledProcessError: non-zero exit status -11

### ISSUE THREAD

**Issue by Qwlouse** [bitsofbits/kaggle_grasp_and_lift_eeg_detection#1]
While reproducing the results I'm having some errors. As far as I can tell this one happened for the first model `net_nds4_150e20_96478`:

```
The network to train: -1
Running nets in parallel
processing net_nds4_150e20_96478
                        ....
       [Lots of Theano logging INFO]
                        ....
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "submission.py", line 119, in worker
    subprocess.check_call(["python", "submission.py", '-r', run_type, '-n', str(i)], stdout=log, env=env
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'submission.py', '-r', 'run', '-n', '0']' returned non-zero exit status -11
```

Interestingly I get a `submissions/net_nds4_150e20_96478.csv.log` file but no CSV and also no model dump files for that model.  

I'm using `Python 3.4.3` with the following library versions on Ubuntu 15.04:

```
Lasagne==0.2.dev1
nolearn==0.6a0.dev0
numpy==1.9.3
pandas==0.16.2
python-dateutil==2.4.2
pytz==2015.6
PyYAML==3.11
scikit-learn==0.16.1
scipy==0.16.0
six==1.9.0
tabulate==0.7.5
Theano==0.7.0
wheel==0.24.0
```

Any ideas?

**Comment by bitsofbits** [comment]
Hi Klaus, I'm sorry that's giving you trouble!

That does indeed look like it's dying on the first entry.  It's unsurprising that you get a log file, that is opened right away, so you'll get that file pretty much no matter what.  Is it just an empty file?

The first thing I'd try is:

```
python submission.py -r dry -n 0
```

This will just attempt to instantiate net #0, this will probably work and not tell us much, but it's easy and quick. Then I'd try:

```
python submission.py -r run -n 0
```

This will attempt train just net #0. It doesn't do any of the multiprocessing shenanigans, so that cuts out a bunch of potential problems. If this fails, can you attach the Theano logging info? 

If it passes, then we're on to figuring out why the multiprocessing stuff is going wrong. In that case the first place to look is going to by SETTINGS.json at the `theano_flags` variable, making sure that it's not trying to use a GPU you don't have.

After that, if it's still not working, I'll have to think about it more. I expect it's something shallow. I'll pass this on to Deep as well and see if he has any ideas.

[EDIT] Said net 1, when I meant net 0. Fixed.

**Comment by esube** [comment]
Hi Klaus, 

FYI, here is the setup in which it was tested and run (only the ones with different version than your list above):

python==2.7

nolearn==0.6adev
numpy==1.9.2
pandas=0.15.2
pytz==2012c
scipy==0.13.3
six==1.5.2

All other deps versions you've listed as same as ours.

[EDIT] 
Btw, The most important part of the error is under the section you labeled as:
                        ....
       [Lots of Theano logging INFO]
                        ....

If you can post more python errors thrown in there, that would help us to pin point the problem more precisely.

**Comment by Qwlouse** [comment]
Never mind. On the second attempt that networks ran fine. I suspect it might be a RAM problem, because the script regularly uses up all of my 16GBs. So I'll just keep restarting until all the networks have been trained successfully.

**Comment by esube** [comment]
We are glad it worked again. Yeah, we also were suspecting memory issues. When you run the parallel version, it uses lots of memory. So, you should either increase your RAM or swap space. Increasing just the swap space, however, will make it slow. Another option is run each network individually in serial manner than using the multi processing. As per the readme, our box had 32G RAM and 20G space initially. We encountered a crash of some of the runs and we ended up increasing the swap space to 220G.

Let us know if there's any more issues.
